# Generated by Django 5.1.1 on 2024-10-17 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_management', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='imagen_url',
            new_name='link',
        ),
        migrations.RemoveField(
            model_name='post',
            name='video_url',
        ),
        migrations.AddField(
            model_name='post',
            name='is_programmed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='post',
            name='programmed_post_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
