# Generated by Django 5.1.1 on 2024-10-20 19:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social_management', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='cuentaredsocial',
            table='vi_cuentaredsocial',
        ),
        migrations.AlterModelTable(
            name='etiqueta',
            table='vi_etiqueta',
        ),
        migrations.AlterModelTable(
            name='interaccion',
            table='vi_interaccion',
        ),
        migrations.AlterModelTable(
            name='post',
            table='vi_post',
        ),
        migrations.AlterModelTable(
            name='postetiqueta',
            table='vi_postetiqueta',
        ),
        migrations.AlterModelTable(
            name='redsocial',
            table='vi_redsocial',
        ),
        migrations.AlterModelTable(
            name='reporteredes',
            table='vi_reporteredes',
        ),
        migrations.AlterModelTable(
            name='segmento',
            table='vi_segmento',
        ),
    ]
