# Generated by Django 5.1.1 on 2024-10-20 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_management', '0002_alter_cuentaredsocial_table_alter_etiqueta_table_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
