# Generated by Django 5.1.1 on 2024-10-17 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_management', '0002_rename_imagen_url_post_link_remove_post_video_url_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='id_red_social',
        ),
        migrations.RemoveField(
            model_name='post',
            name='usuario_creacion',
        ),
        migrations.RemoveField(
            model_name='post',
            name='usuario_modificacion',
        ),
        migrations.AddField(
            model_name='post',
            name='media',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='preview',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='red_social',
            field=models.CharField(choices=[('TikTok', 'TikTok'), ('Facebook', 'Facebook'), ('Instagram', 'Instagram')], default='Facebook', max_length=255),
        ),
        migrations.AddField(
            model_name='post',
            name='tipo',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
