# Generated by Django 5.1.1 on 2024-10-20 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_management', '0004_remove_post_link_post_is_programmed'),
    ]

    operations = [
        migrations.AddField(
            model_name='cuentaredsocial',
            name='open_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
