# Generated by Django 5.1.1 on 2024-10-02 10:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer_analytics', '0001_initial'),
        ('marketing_campaigns', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='campanausuario',
            name='usuario_id',
        ),
        migrations.AddField(
            model_name='campanausuario',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='customer_analytics.usuario'),
        ),
    ]
