# Generated by Django 5.1.1 on 2024-10-20 20:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketing_campaigns', '0002_remove_campanausuario_usuario_id_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='anuncio',
            table='vi_anuncio',
        ),
        migrations.AlterModelTable(
            name='campana',
            table='vi_campana',
        ),
        migrations.AlterModelTable(
            name='campanausuario',
            table='vi_campana_usuario',
        ),
        migrations.AlterModelTable(
            name='postcampana',
            table='vi_post_campana',
        ),
    ]
